#storage:
#  type: fileSystem
#  properties:
#    path: C:\file
#storage:
#  type: metadata
#  properties:
#    path: C:\file
#    format: json
storage:
  type: s3
  properties:
    accessKey: akey
    secretKey: skey
    bucketName: bname
