storage:
  type: fileSystem
  properties:
    path: D:\upload\
#storage:
#  type: metadata
#  properties:
#    path: D:\upload\
#    format: json
#storage:
#  type: s3
#  properties:
#    accessKey: akey
#    secretKey: skey
#    bucketName: bname
